--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alan/Imagens/wallpapers/70.jpg"

-- Special
background="#1b1e25"
foreground="#e6d2ba"
cursor="#e6d2ba"

-- Colors
color0="#1b1e25"
color1="#C5716D"
color2="#AD8C75"
color3="#D49676"
color4="#556F8B"
color5="#6D889C"
color6="#959796"
color7="#e6d2ba"
color8="#a19382"
color9="#C5716D"
color10="#AD8C75"
color11="#D49676"
color12="#556F8B"
color13="#6D889C"
color14="#959796"
color15="#e6d2ba"
