# Shell variables
# Generated by 'wal'
wallpaper='/home/alan/Imagens/wallpapers/70.jpg'

# Special
background='#1b1e25'
foreground='#e6d2ba'
cursor='#e6d2ba'

# Colors
color0='#1b1e25'
color1='#C5716D'
color2='#AD8C75'
color3='#D49676'
color4='#556F8B'
color5='#6D889C'
color6='#959796'
color7='#e6d2ba'
color8='#a19382'
color9='#C5716D'
color10='#AD8C75'
color11='#D49676'
color12='#556F8B'
color13='#6D889C'
color14='#959796'
color15='#e6d2ba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
